name: Build latest master and deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, self-hosted ]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.12.0
        with:
          java-version: 22
          java-distribution: liberica
          checkout-persist-credentials: true
          cache-enabled: false

      - name: Build with Maven
        run: mvn clean package -Pnative
